include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    # unnecessary_breaks: true
