name: mood_picker_example
description: A Flutter project to demonstrate MoodMeterPicker usage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mood_meter_picker:
    path: ../
  riverpod_annotation: ^2.1.6
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.2.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
