name: mood_picker_example
description: A Flutter project to demonstrate MoodMeterPicker usage.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.0-0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.7.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mood_meter_picker:
    path: ../
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  go_router_builder: ^2.7.5
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
