name: mood_meter_picker
description: A Flutter package project that tries to implement Mood Meter Picker from https://moodmeterapp.com/science/.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_portal: ^1.1.4
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
