name: mood_meter_picker
description: A Flutter package project that tries to implement Mood Meter Picker from https://moodmeterapp.com/science/.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.21.0'

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_portal: ^1.1.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
