name: mood_meter_picker
description: A Flutter package project that tries to implement Mood Meter Picker from https://moodmeterapp.com/science/.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_portal: ^1.1.4
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
