name: mood_meter_picker
description: A Flutter package project that tries to implement Mood Meter Picker from https://moodmeterapp.com/science/.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_portal: ^1.1.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
